### ISSUE TITLE
dashboard 没显示任何数据

### ISSUE THREAD

**Issue by CheckyChen** [SkyAPM/SkyAPM-dotnet#334]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
按照说明的示例 新建的sample_app项目，在skywalking看板中，为什么没有显示任何图表数据？
sample_app logs文件夹中的日志和skywalking的日志中都没看到异常日志
___
### Bug
- Windows 10,.Net Core 3.1,SkyWalking 8.1.0
- Nuget Package:  SkyAPM.Agent.AspNetCore 1.0.0
- skyapm.json
``` json
{
  "SkyWalking": {
    "ServiceName": "sample_app",
    "Namespace": "",
    "HeaderVersions": [
      "sw8"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v6",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "127.0.0.1:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000
      }
    }
  }
}
```
- application.yml
``` yml
storage:
  selector: ${SW_STORAGE:elasticsearch7}
  elasticsearch7:
    nameSpace: ${SW_NAMESPACE:""}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
    protocol: ${SW_STORAGE_ES_HTTP_PROTOCOL:"http"}
    trustStorePath: ${SW_STORAGE_ES_SSL_JKS_PATH:""}
    trustStorePass: ${SW_STORAGE_ES_SSL_JKS_PASS:""}
    dayStep: ${SW_STORAGE_DAY_STEP:1} # Represent the number of days in the one minute/hour/day index.
    user: ${SW_ES_USER:""}
    password: ${SW_ES_PASSWORD:""}
    secretsManagementFile: ${SW_ES_SECRETS_MANAGEMENT_FILE:""} # Secrets management file in the properties format includes the username, password, which are managed by 3rd party tool.
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:1} # Shard number of new indexes
    superDatasetIndexShardsFactor: ${SW_STORAGE_ES_SUPER_DATASET_INDEX_SHARDS_FACTOR:5} # Super data set has been defined in the codes, such as trace segments. This factor provides more shards for the super data set, shards number = indexShardsNumber * superDatasetIndexShardsFactor. Also, this factor effects Zipkin and Jaeger traces.
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:0}
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:1000} # Execute the bulk every 1000 requests
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
    resultWindowMaxSize: ${SW_STORAGE_ES_QUERY_MAX_WINDOW_SIZE:10000}
    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
    profileTaskQueryMaxSize: ${SW_STORAGE_ES_QUERY_PROFILE_TASK_SIZE:200}
    advanced: ${SW_STORAGE_ES_ADVANCED:""}
```
UI看不到任何数据：
![image](https://user-images.githubusercontent.com/15060877/96248314-f3f46000-0fdd-11eb-81da-7b6e0ee29e11.png)

![image](https://user-images.githubusercontent.com/15060877/96251360-ea212b80-0fe2-11eb-959f-08730b41f3b3.png)

![image](https://user-images.githubusercontent.com/15060877/96251296-d07fe400-0fe2-11eb-9b61-1a8f7b8c98cf.png)

![image](https://user-images.githubusercontent.com/15060877/96251326-daa1e280-0fe2-11eb-800b-49fdb8b51335.png)

- skyapm-20201016.log
> 2020-10-16 18:25:15.438 +08:00 [sample_app] [Information] SkyApm.Service.PingService : Ping server @2020/10/16 10:25:15 +00:00
2020-10-16 18:25:45.433 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 16M ThreadPool 32759 32767 1000 1000
2020-10-16 18:26:15.422 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 16M ThreadPool 32759 32767 1000 1000
2020-10-16 18:26:15.422 +08:00 [sample_app] [Information] SkyApm.Service.PingService : Ping server @2020/10/16 10:26:15 +00:00
2020-10-16 18:26:45.434 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 17M ThreadPool 32761 32767 1000 1000
2020-10-16 18:27:15.422 +08:00 [sample_app] [Information] SkyApm.Service.PingService : Ping server @2020/10/16 10:27:15 +00:00
2020-10-16 18:27:15.422 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 17M ThreadPool 32762 32767 1000 1000
2020-10-16 18:27:45.422 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 17M ThreadPool 32760 32767 1000 1000
2020-10-16 18:28:15.437 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 17M ThreadPool 32759 32767 1000 1000
2020-10-16 18:28:15.437 +08:00 [sample_app] [Information] SkyApm.Service.PingService : Ping server @2020/10/16 10:28:15 +00:00

[skywalking-oap-server.log](https://github.com/SkyAPM/SkyAPM-dotnet/files/5391074/skywalking-oap-server.log)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
