### ISSUE TITLE
日志无法写入

### ISSUE THREAD

**Issue by li-zheng-hao** [SkyAPM/SkyAPM-dotnet#522]
- Why do you submit this issue?

Bug

___

### Bug
- Which version of SkyWalking, OS and .NET Runtime?

1. 系统: windows 10
2. Net: .Net 6 Webapi
3. Skywalking: docker-compose部署，配置如下:

```yaml
version: "3"
services:
  oap:
      image: apache/skywalking-oap-server:latest
      ports:
      - 12800:12800
      - 11800:11800
  ui:
      image: apache/skywalking-ui:latest
      ports:
      - "8080:8080/tcp"
      environment:
        SW_OAP_ADDRESS: http://oap:12800
```

- What happen?

日志无法写入Skywalking服务端，下面是Controller代码：

```C#
public WeatherForecastController(ILogger<WeatherForecastController> logger,ILoggerFactory skyapmlogger, IAuthRestClient authRestClient,ITracingContext tracingContext, IEntrySegmentContextAccessor  segContext)
{
    _skyapmlogger = skyapmlogger;
    _tracingContext = tracingContext;
    _segContext = segContext;
    _authRestClient = authRestClient;
    _logger = logger;
}
[HttpGet]
public string HelloWorld(string msg)
{
    //获取全局的skywalking的TracId
    var TraceId = _segContext.Context.TraceId;
    Console.WriteLine($"TraceId={TraceId}");
    _logger.LogInformation("测试Serilog写入Skywalking");
    var logger = _skyapmlogger.CreateLogger("logger");
    var logger2 = _skyapmlogger.CreateLogger(typeof(SkyApmLogger));
    logger.LogInformation("测试官方的Logger");
    logger2.LogInformation("测试官方的Logger");
    _segContext.Context.Span.AddLog(LogEvent.Message($"UserService调用---Worker running at: {DateTime.Now}"));
    return msg;
}
```

只有`_segContext.Context.Span.AddLog`有效，其他日志都没看到，如下图：

![image](https://user-images.githubusercontent.com/22129824/199641161-3ca671fc-edc0-43c7-9922-99f255695acf.png)
![image](https://user-images.githubusercontent.com/22129824/199641244-394e2d32-f3d1-40f4-96cb-b8da4fbc959d.png)

刚开始使用Skywalking，没找到.Net的文档，是我的日志输出方式有问题吗？还是配置不对？
